"""Create or update a Hugging Face Space from this repository.

    python scripts/deploy_space.py --space my-user/nexusrag-staging --environment staging
    python scripts/deploy_space.py --space my-user/nexusrag --environment production --wait

Needs a write token in ``HF_TOKEN``. The Space is a Docker Space that builds this
repository's Dockerfile, so the deployed image is the one CI tests.

Only code is uploaded. Secrets (``GEMINI_API_KEY``, ``AUTH_PASSWORD``,
``CHAINLIT_AUTH_SECRET``) are set once in the Space's own settings and never travel
through this script; it only sets non-secret variables such as ``ENVIRONMENT``.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from collections.abc import Sequence
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]

#: Front matter tells Spaces how to build and which port to expose; the body is what
#: visitors read on the Space page.
SPACE_README = """\
---
title: {title}
emoji: 🔎
colorFrom: indigo
colorTo: blue
sdk: docker
app_port: {port}
pinned: false
short_description: Grounded answers with citations over your own documents
---

# {title}

Advanced RAG chatbot: hybrid search, reranking, a self-correcting agent and inline
citations, built on Chainlit + ChromaDB + Google Gemini.

- **Source and documentation:** <https://github.com/{repo}>
- **Environment:** `{environment}`

Ask about the sample corpus (a fictional drone company): battery life, return policy,
remote-work stipends, quarterly revenue. Every answer cites the passage it came from, and
the pipeline's steps are shown with their timings.

*Deployed automatically from the `{branch}` branch; this file is generated by
`scripts/deploy_space.py`.*
"""

#: Never upload local state, secrets, tests or evaluation artefacts to a public Space.
IGNORE = [
    ".git/*",
    ".github/*",
    ".venv/*",
    "**/__pycache__/*",
    "**/.pytest_cache/*",
    "**/.mypy_cache/*",
    "**/.ruff_cache/*",
    ".env",
    ".env.*",
    "storage/*",
    ".files/*",
    "*.db",
    "*.db-*",
    "tests/*",
    "eval/*",
    "README.md",  # replaced by the Space README below
]


def space_readme(title: str, repo: str, environment: str, branch: str, port: int) -> str:
    return SPACE_README.format(
        title=title, repo=repo, environment=environment, branch=branch, port=port
    )


def deploy(
    api: Any,
    space: str,
    *,
    environment: str,
    branch: str,
    repo: str,
    port: int,
    commit_message: str,
) -> str:
    """Create the Space if needed, set its variables and upload the code. Returns its URL."""
    api.create_repo(repo_id=space, repo_type="space", space_sdk="docker", exist_ok=True)
    for key, value in {
        "ENVIRONMENT": environment,
        "PORT": str(port),
        "BOOTSTRAP_INDEX": "true",
        # Spaces without paid persistent storage reset on restart; index into the
        # container's own writable directory and rebuild from data/ on each cold start.
        "STORAGE_DIR": "/data/storage",
    }.items():
        api.add_space_variable(repo_id=space, key=key, value=value)
    title = space.split("/")[-1]
    api.upload_file(
        path_or_fileobj=space_readme(title, repo, environment, branch, port).encode("utf-8"),
        path_in_repo="README.md",
        repo_id=space,
        repo_type="space",
        commit_message=commit_message,
    )
    api.upload_folder(
        folder_path=str(REPO_ROOT),
        repo_id=space,
        repo_type="space",
        ignore_patterns=IGNORE,
        commit_message=commit_message,
    )
    return f"https://huggingface.co/spaces/{space}"


def wait_until_running(api: Any, space: str, *, timeout_s: float, interval_s: float = 15) -> str:
    """Poll the Space until it is running; returns the final stage."""
    deadline = time.monotonic() + timeout_s
    stage = "UNKNOWN"
    while time.monotonic() < deadline:
        stage = str(getattr(api.get_space_runtime(repo_id=space), "stage", "UNKNOWN"))
        print(f"Space stage: {stage}", file=sys.stderr, flush=True)
        if stage == "RUNNING":
            return stage
        if "ERROR" in stage or stage in ("STOPPED", "PAUSED", "DELETING"):
            return stage  # building/starting stages keep polling
        time.sleep(interval_s)
    return stage


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--space", required=True, help="owner/name of the Space")
    parser.add_argument("--environment", default="staging", choices=["staging", "production"])
    parser.add_argument("--branch", default="staging", help="branch this deploy came from")
    parser.add_argument("--repo", default="Neel-Khandelwal-03/nexusrag", help="GitHub repository")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--message", default=None, help="commit message for the Space")
    parser.add_argument("--wait", action="store_true", help="wait until the Space is running")
    parser.add_argument("--timeout", type=float, default=900, help="seconds to wait")
    args = parser.parse_args(argv)

    token = os.environ.get("HF_TOKEN")
    if not token:
        parser.error("HF_TOKEN is not set (a Hugging Face write token is required)")

    from huggingface_hub import HfApi  # imported here so --help works without the package

    api = HfApi(token=token)
    url = deploy(
        api,
        args.space,
        environment=args.environment,
        branch=args.branch,
        repo=args.repo,
        port=args.port,
        commit_message=args.message or f"Deploy from {args.branch}",
    )
    print(f"Deployed to {url}", file=sys.stderr)
    if args.wait:
        stage = wait_until_running(api, args.space, timeout_s=args.timeout)
        if stage != "RUNNING":
            print(f"Space did not reach RUNNING (last stage: {stage})", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
